export const metadata = {
  title: "Privacy Policy – Zelo",
};

export default function PrivacyPage() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-16 text-sm leading-relaxed">
      <h1 className="text-2xl font-semibold mb-2">Privacy Policy</h1>
      <p className="text-gray-500 mb-8">Last updated: April 9, 2025</p>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">1. Overview</h2>
        <p>
          Zelo (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) provides an
          AI-powered sales assistant that communicates with customers via
          Instagram Direct Messages on behalf of businesses. This policy
          explains what data we collect, how we use it, and your rights.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">2. Data We Collect</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Instagram sender IDs and message text from incoming DMs</li>
          <li>Responses generated by our AI and sent back to users</li>
          <li>Basic metadata from Meta webhook events (timestamps, page IDs)</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">3. How We Use Data</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>To generate and send automated replies to Instagram DMs</li>
          <li>To improve the quality and accuracy of AI responses</li>
          <li>To operate and maintain the service</li>
        </ul>
        <p className="mt-2">
          We do not sell or share your data with third parties except as
          required to operate the service (Meta Graph API, OpenAI API).
        </p>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">4. Third-Party Services</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>
            <strong>Meta (Instagram)</strong> – messages are received and sent
            via the Meta Graph API under Meta&apos;s{" "}
            <a
              href="https://www.facebook.com/privacy/policy/"
              className="underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              Privacy Policy
            </a>
            .
          </li>
          <li>
            <strong>OpenAI</strong> – message text is sent to OpenAI to
            generate replies, subject to{" "}
            <a
              href="https://openai.com/policies/privacy-policy"
              className="underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              OpenAI&apos;s Privacy Policy
            </a>
            .
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">5. Data Retention</h2>
        <p>
          Message content is processed in real time and is not stored
          persistently by Zelo beyond server request logs, which are retained
          for up to 30 days.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">6. Your Rights</h2>
        <p>
          You may request access to, correction of, or deletion of any personal
          data we hold by contacting us at the email below.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="font-semibold mb-2">7. Contact</h2>
        <p>
          For privacy-related questions, contact us at{" "}
          <a href="mailto:alfonziazri@gmail.com" className="underline">
            alfonziazri@gmail.com
          </a>
          .
        </p>
      </section>
    </main>
  );
}
